services:
  mariadb:
    image: mariadb:11
    container_name: mariadb-dev
    restart: always
    ports:
      - '3306:3306'
    volumes:
      - mariadb-dev-data:/var/lib/mysql

volumes:
  mariadb-dev-data:
