services:
  mariadb-test:
    image: mariadb:11
    container_name: mariadb-test
    restart: always
    ports:
      - '3307:3306'
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: apptestdb
      MYSQL_USER: apptestuser
      MYSQL_PASSWORD: mytestpassword
    volumes:
      - mariadb-test-data:/var/lib/mysql

volumes:
  mariadb-test-data:

